[package]
name = "file_generator"
version = "1.0.0"
authors = ["user"]
edition = "2018"
publish = false

[dependencies]
synth_library = {package = "synth_library", path = "../synth_library" }

rand = ""
# json = "*"
serde = {version="", features=["derive"]}
serde_json = ""
log = ""
log4rs = ""