[package]
name = "synth_library"
version = "1.0.0"
authors = ["user"]
edition = "2018"
publish = false

[dependencies]
rand = "*"
chrono = "*"
time = "*"
uuid = { version = "*", features = ["serde", "v4"] }
log = "*"
log4rs = "*"